# This rule is not used by the project proxmox-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to vitistack.io.vitistack.io resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: proxmox-operator
    app.kubernetes.io/managed-by: kustomize
  name: kubernetescluster-viewer-role
rules:
- apiGroups:
  - vitistack.io.vitistack.io
  resources:
  - kubernetesclusters
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - vitistack.io.vitistack.io
  resources:
  - kubernetesclusters/status
  verbs:
  - get
