---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - vitistack.io
  resources:
  - machineproviders
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - vitistack.io
  resources:
  - machines
  - networkconfigurations
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - vitistack.io
  resources:
  - machines/finalizers
  verbs:
  - update
- apiGroups:
  - vitistack.io
  resources:
  - machines/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - vitistack.io
  resources:
  - networkconfigurations/status
  verbs:
  - get
  - watch
- apiGroups:
  - vitistack.io
  resources:
  - networknamespaces
  - vitistacks
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - vitistack.io
  resources:
  - networknamespaces/status
  verbs:
  - get
