package consts

const (
	DEVELOPMENT             = "DEVELOPMENT"
	LOG_LEVEL               = "LOG_LEVEL"
	LOG_JSON                = "LOG_JSON"
	LOG_ADD_CALLER          = "LOG_ADD_CALLER"
	LOG_DISABLE_STACKTRACE  = "LOG_DISABLE_STACKTRACE"
	LOG_UNESCAPED_MULTILINE = "LOG_UNESCAPED_MULTILINE"
	LOG_COLORIZE_LINE       = "LOG_COLORIZE_LINE"
	IP_SOURCE               = "IP_SOURCE"
	VITISTACK_NAME          = "VITISTACK_NAME"
	NAME_MACHINE_PROVIDER   = "NAME_MACHINE_PROVIDER"

	// Proxmox settings
	PROXMOX_ENDPOINT          = "PROXMOX_ENDPOINT"
	PROXMOX_USERNAME          = "PROXMOX_USERNAME"
	PROXMOX_PASSWORD          = "PROXMOX_PASSWORD"     // #nosec G101 - This is just an env var key name
	PROXMOX_TOKEN_ID          = "PROXMOX_TOKEN_ID"     // #nosec G101 - This is just an env var key name
	PROXMOX_TOKEN_SECRET      = "PROXMOX_TOKEN_SECRET" // #nosec G101 - This is just an env var key name
	PROXMOX_INSECURE_TLS      = "PROXMOX_INSECURE_TLS"
	PROXMOX_VM_ID_START       = "PROXMOX_VM_ID_START"
	PROXMOX_ALLOWED_NODES     = "PROXMOX_ALLOWED_NODES"
	PROXMOX_NODE_SELECTION    = "PROXMOX_NODE_SELECTION"
	PROXMOX_DEFAULT_STORAGE   = "PROXMOX_DEFAULT_STORAGE"
	PROXMOX_DEFAULT_NETWORK   = "PROXMOX_DEFAULT_NETWORK"
	PROXMOX_NETWORK_MODEL     = "PROXMOX_NETWORK_MODEL"
	PROXMOX_DEFAULT_CPU_TYPE  = "PROXMOX_DEFAULT_CPU_TYPE"
	PROXMOX_ENABLE_NUMA       = "PROXMOX_ENABLE_NUMA"
	PROXMOX_SCSI_CONTROLLER   = "PROXMOX_SCSI_CONTROLLER"
	PROXMOX_ENABLE_QEMU_AGENT = "PROXMOX_ENABLE_QEMU_AGENT"
	PROXMOX_START_ON_CREATE   = "PROXMOX_START_ON_CREATE"
	PROXMOX_DEFAULT_VLAN      = "PROXMOX_DEFAULT_VLAN"
	PROXMOX_DEFAULT_MTU       = "PROXMOX_DEFAULT_MTU"

	MAC_SET = "MAC_SET"

	// Proxmox disk controller slot names
	DiskSlotSCSI0   = "scsi0"
	DiskSlotVirtIO0 = "virtio0"
	DiskSlotSATA0   = "sata0"
	DiskSlotIDE0    = "ide0"

	// Proxmox network slot names
	NetSlot0 = "net0"

	// Default values
	DefaultDiskSizeGB   = 50
	DefaultNetworkModel = "virtio"
)
